# Site settings
title: 潜龙勿用
header-img: "img/facebook.jpg"
tagline: "cn"  
description: "秦至|读而立·写而生"  
baseurl: ""
url: "http://Damonare.github.io"  

# About/contact
owner: 
  name: " 秦至"
  email: jztan1996@outlook.com
  bio: "写就是写的报酬"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username: 谭继臻
twitter_username: 
github_username: Damonare
weibo_username: Damonare
facebook_username: 秦至
zhihu_username: jztan

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
relative_permalinks: false

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "秦至"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 秦至
  disqus :
      short_name : 秦至

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
